Feature/additional gloss info
UUDigitalHumanitieslab/igtdetect pull request #3
Opened 2023-06-08 13:27 UTC by Meesch

This branch adds prefix and grammaticality fields to the IGT class. It removes the prefix from the utterance, but not the grammaticality marker.

2023-06-08 14:11 UTC, bbonf requested changes

2023-06-08 14:11 UTC, bbonf commented on igtdetect/glossharvester.py
> +            next_prefix = detect_prefix(' '.join(words[1:]))
This is fine, we don't expect too many prefixes per line, but it could be nicely written as a single loop that stops on the first non-prefix word

2023-06-08 14:11 UTC, bbonf commented on igtdetect/glossharvester.py
> +        grammaticality_marker = re.search(r"\*|\?|\#|\%", words[0][0])
`words[0][0]` is a single character right? Then you can do this instead: `words[0][0] in '*?#%'`

2023-06-08 14:11 UTC, bbonf commented on igtdetect/pdf2gloss.py
> +        meta.set('classifaction_methods', item.classification_methods)
Still a typo :) how about `reason` or `selected_by`

2023-06-08 14:11 UTC, bbonf commented on igtdetect/glossharvester.py
> +            utterance = utterance.replace(pf, '')
I think this might be too strong. If your prefix is 'a.' then `Jan collected the data.` becomes `Jan collected the dat`

2023-06-08 14:11 UTC, bbonf commented on igtdetect/glossharvester.py
> +            utterance = utterance.replace(pf, '')
I would make a slice using the length of the prefix `utterance[len(pf):]`

2023-06-08 15:00 UTC, Meesch commented on igtdetect/glossharvester.py
> +            next_prefix = detect_prefix(' '.join(words[1:]))
Ben, you leave me these comments and they make me a better programmer. Perfect end-of-day programming exercises.

2023-06-08 15:04 UTC, Meesch commented on igtdetect/glossharvester.py
> +            utterance = utterance.replace(pf, '')
actually, I've used your other mindblower and just gave it a count argument.

2023-06-08 15:05 UTC, Meesch commented
I think I addressed all your comments, thank you for the in-depth feedback and little exercise!

2023-06-09 07:20 UTC, bbonf approved these changes

2023-06-09 08:38 UTC, merged